package com.tube.tv.data

import android.net.Uri
import com.tube.tv.domain.AudioVariant
import com.tube.tv.domain.Chapter
import com.tube.tv.domain.ResolvedMedia
import com.tube.tv.domain.StreamResolver
import com.tube.tv.domain.SubtitleTrack
import com.tube.tv.domain.VideoVariant
import okhttp3.OkHttpClient
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamType

/**
 * All YouTube-specific extraction lives here. The result keeps only what playback needs;
 * the (large) StreamInfo, related-video lists etc. are dropped immediately.
 */
class NewPipeStreamResolver(private val client: OkHttpClient) : StreamResolver {

    @Volatile private var cached: ResolvedMedia? = null

    override suspend fun resolve(videoId: String, forceRefresh: Boolean): ResolvedMedia {
        cached?.let {
            if (!forceRefresh && it.videoId == videoId && it.expiresAtMs - EXPIRY_MARGIN_MS > System.currentTimeMillis()) {
                return it
            }
        }
        val media = blockingIo(client) {
            map(videoId, StreamInfo.getInfo(ServiceList.YouTube, "https://www.youtube.com/watch?v=$videoId"))
        }
        cached = media
        return media
    }

    override fun invalidate() {
        cached = null
    }

    private fun map(videoId: String, info: StreamInfo): ResolvedMedia {
        val live = info.streamType == StreamType.LIVE_STREAM || info.streamType == StreamType.AUDIO_LIVE_STREAM

        val video = (info.videoOnlyStreams + info.videoStreams)
            .filter { it.isUrl && it.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP && it.format != null }
            .map {
                VideoVariant(
                    url = it.content,
                    mimeType = it.format!!.mimeType,
                    codec = it.codec.orEmpty(),
                    width = it.width,
                    height = it.height,
                    fps = it.fps,
                    bitrate = it.bitrate,
                    videoOnly = it.isVideoOnly,
                )
            }
            .filter { it.height > 0 && it.codec.isNotEmpty() }

        val audio = info.audioStreams
            .filter { it.isUrl && it.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP && it.format != null }
            .map {
                AudioVariant(
                    url = it.content,
                    mimeType = it.format!!.mimeType,
                    codec = it.codec.orEmpty(),
                    bitrate = it.averageBitrate,
                    trackId = it.audioTrackId,
                    language = it.audioLocale?.language,
                    label = it.audioTrackName,
                    isOriginal = it.audioTrackType?.name == "ORIGINAL",
                    isDescriptive = it.audioTrackType?.name == "DESCRIPTIVE",
                )
            }

        val subtitles = info.subtitles
            .filter { it.isUrl && it.format != null }
            .mapNotNull {
                val mime = it.format!!.mimeType
                if (mime != "text/vtt" && mime != "application/ttml+xml") return@mapNotNull null
                SubtitleTrack(
                    url = it.content,
                    mimeType = mime,
                    languageTag = it.languageTag.orEmpty(),
                    label = it.displayLanguageName.orEmpty(),
                    autoGenerated = it.isAutoGenerated,
                )
            }

        val chapters = info.streamSegments.map { Chapter(it.title.orEmpty(), it.startTimeSeconds * 1000L) }

        val expiry = video.firstOrNull()?.url?.let { expiryOf(it) }
            ?.coerceAtMost(audio.firstOrNull()?.url?.let { expiryOf(it) } ?: Long.MAX_VALUE)
            ?: (System.currentTimeMillis() + DEFAULT_TTL_MS)

        return ResolvedMedia(
            videoId = videoId,
            title = info.name.orEmpty(),
            channel = info.uploaderName.orEmpty(),
            durationMs = if (live) 0 else info.duration * 1000L,
            thumbnailUrl = info.thumbnails.maxByOrNull { it.width }?.url,
            isLive = live,
            hlsUrl = if (live) info.hlsUrl?.takeIf { it.isNotEmpty() } else null,
            videoStreams = video,
            audioStreams = audio,
            subtitles = subtitles,
            chapters = chapters,
            expiresAtMs = expiry,
        )
    }

    private fun expiryOf(url: String): Long? =
        Uri.parse(url).getQueryParameter("expire")?.toLongOrNull()?.times(1000)

    private companion object {
        const val EXPIRY_MARGIN_MS = 60_000L
        const val DEFAULT_TTL_MS = 30 * 60_000L
    }
}
