package com.tube.tv.domain

/** Items shown in browse lists. Pure app models: no extractor types leak past the data layer. */
sealed interface BrowseItem {
    val id: String
    val title: String
    val thumbnailUrl: String?
}

data class VideoItem(
    val videoId: String,
    override val title: String,
    val channelName: String,
    val durationSeconds: Long,
    override val thumbnailUrl: String?,
    val published: String?,
    val isLive: Boolean,
) : BrowseItem {
    override val id: String get() = "v:$videoId"
}

data class ChannelItem(
    val channelUrl: String,
    val name: String,
    override val thumbnailUrl: String?,
    val subscribers: Long,
) : BrowseItem {
    override val id: String get() = "c:$channelUrl"
    override val title: String get() = name
}

data class PlaylistItem(
    val playlistUrl: String,
    val name: String,
    val uploader: String,
    val videoCount: Long,
    override val thumbnailUrl: String?,
) : BrowseItem {
    override val id: String get() = "p:$playlistUrl"
    override val title: String get() = name
}

/** A local viewer profile. Each has its own YouTube sign-in and resume positions. */
data class Profile(val id: String, val name: String, val colorIndex: Int)

/** Opaque continuation token owned by the data layer. */
@JvmInline
value class PageToken(val raw: Any)

data class ResultPage<T>(val items: List<T>, val next: PageToken?)

// ---- Stream resolution output (consumed by the playback layer) ----

data class VideoVariant(
    val url: String,
    val mimeType: String,
    val codec: String,
    val width: Int,
    val height: Int,
    val fps: Int,
    val bitrate: Int,
    val videoOnly: Boolean,
) {
    val isHdr: Boolean
        get() = codec.startsWith("vp09.02") || codec.startsWith("vp9.2") ||
            (codec.startsWith("av01") && codec.split('.').getOrNull(3) == "10")

    /** Stable identity used to exclude a variant after a decoder failure. */
    val key: String get() = "$mimeType|$codec|$width|$height|$fps|$bitrate"
}

data class AudioVariant(
    val url: String,
    val mimeType: String,
    val codec: String,
    val bitrate: Int,
    val trackId: String?,
    val language: String?,
    val label: String?,
    val isOriginal: Boolean,
    val isDescriptive: Boolean,
)

data class SubtitleTrack(
    val url: String,
    val mimeType: String,
    val languageTag: String,
    val label: String,
    val autoGenerated: Boolean,
)

data class Chapter(val title: String, val startMs: Long)

data class ResolvedMedia(
    val videoId: String,
    val title: String,
    val channel: String,
    val durationMs: Long,
    val thumbnailUrl: String?,
    val isLive: Boolean,
    val hlsUrl: String?,
    val videoStreams: List<VideoVariant>,
    val audioStreams: List<AudioVariant>,
    val subtitles: List<SubtitleTrack>,
    val chapters: List<Chapter>,
    /** Wall-clock time (ms) after which the stream URLs stop working. */
    val expiresAtMs: Long,
)

enum class ErrorKind {
    UNAVAILABLE, AGE_RESTRICTED, REGION_RESTRICTED, PRIVATE, REMOVED,
    NETWORK, EXTRACTION, UNSUPPORTED_CODEC, STREAM_EXPIRED, SIGNED_OUT, UNKNOWN,
}

class ContentException(val kind: ErrorKind, cause: Throwable? = null, detail: String? = null) :
    Exception(kind.name, cause) {
    /** Technical one-liner shown under the friendly message so failures can be reported precisely. */
    val detail: String? = detail ?: cause?.let { "${it.javaClass.simpleName}: ${it.message}".take(200) }
}
